[package]
name = "toml_edit"
version = "0.1.0"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["toml"]
categories = ["encoding", "parser-implementations", "parsing"]
description = "Yet another format-preserving TOML parser."
authors = ["Andronik Ordian <write@reusable.software>"]
homepage = "https://github.com/ordian/toml_edit"
repository = "https://github.com/ordian/toml_edit"
documentation = "https://docs.rs/toml_edit"

[badges]
travis-ci = { repository = "ordian/toml_edit" }
appveyor = { repository = "ordian/toml_edit" }

[dependencies]
chrono = "0.4"
intrusive-collections = "0.6"
linked-hash-map = "0.4"
nom_locate = "0.1.0"
typed-arena = "1.3"
nom = { version = "3.2", features = ["verbose-errors"] }

[dev-dependencies]
serde_json = "1.0"

[profile.dev]
opt-level = 1
